# Generated by Django 4.1.4 on 2023-02-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressuser',
            name='medal',
        ),
    ]
