# Generated by Django 4.1.4 on 2023-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_user', '0002_remove_addressuser_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
