# Generated by Django 4.1.4 on 2023-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_user', '0002_alter_datauser_options_alter_datauser_cell_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='datauser',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
