# Generated by Django 4.1.4 on 2023-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressuser',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='type_address',
            field=models.CharField(choices=[('casa', 'Casa'), ('trabalho', 'Trabalho')], default=False, max_length=8, verbose_name='Este é o seu trabalho ou sua casa?'),
        ),
    ]
