# Generated by Django 4.1.4 on 2023-02-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_addressuser_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuser',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
    ]
